## 데이터불러오기

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import mglearn
from matplotlib import font_manager, rc 

font_name=font_manager.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name() 
rc('font', family=font_name) 

In [ ]:
df_train = pd.read_csv("C:/users/yhg31/OneDrive/바탕 화면/데이터파일/2021 학술제 데이터/Subject_C.csv")
df_test = pd.read_csv("C:/users/yhg31/OneDrive/바탕 화면/데이터파일/2021 학술제 데이터/Subject_C_testset.csv")

In [ ]:
#용량 줄이는 코드
import numpy as np

def reduce_mem_usage(df):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.        
    """

    for col in df.columns:
        col_type = df[col].dtype

        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)

    return df
df_train = reduce_mem_usage(df_train)
df_train.info()

In [ ]:
df_train

In [ ]:
df_train["Class"].value_counts()

In [ ]:
col_list=df_train.columns[1:]
col_list1=[]
for i in range(len(col_list)):
    col_list1.append(col_list[i].split(" ")[0])
col_list1
set(col_list1)

In [ ]:
df_train[df_train.duplicated()]

In [ ]:
df_train.info()

In [25]:
df_train.describe()

Class  AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  \
count  2400.000000    2400.000000  2400.000000    2400.000000  2400.000000   
mean      1.000000            inf          inf       1.090820     2.664062   
std       0.816667       8.570312     5.410156       0.515625     1.031250   
min       0.000000    3512.000000  2035.000000       0.075623     0.599121   
25%       0.000000    3568.000000  2062.000000       0.736328     2.113281   
50%       1.000000    3572.000000  2066.000000       1.018555     2.530273   
75%       2.000000    3576.000000  2068.000000       1.361328     3.031250   
max       2.000000    3622.000000  2098.000000       4.199219    14.617188   

       AF3 alpha std  AF3 alpha m  AF3 beta std   AF3 beta m  F7 delta std  \
count    2400.000000  2400.000000   2400.000000  2400.000000   2400.000000   
mean        1.017578     2.466797      3.273438     4.160156           inf   
std         0.443848     0.752441      0.768066     0.579590      2.398438   
min         0.121094     0.601074      1.361328     2.626953   3564.000000   
25%         0.691895     1.969238      2.713867     3.748047   3574.000000   
50%         0.971436     2.374023      3.204102     4.117188   3576.000000   
75%         1.281494     2.859863      3.796875     4.511719   3576.000000   
max         2.818359     8.070312      5.574219     6.664062   3580.000000   

       ...  F8 beta std    F8 beta m  AF4 delta std  AF4 delta m  \
count  ...  2400.000000  2400.000000     2400.00000  2400.000000   
mean   ...     4.847656     9.007812            inf          inf   
std    ...     1.452148     4.828125       33.28125    21.421875   
min    ...     1.821289     3.484375     3428.00000  2010.000000   
25%    ...     3.853027     6.035156     3550.00000  2062.000000   
50%    ...     4.601562     7.562500     3568.00000  2072.000000   
75%    ...     5.559570    10.306641     3586.00000  2084.000000   
max    ...    17.234375    53.468750     3738.00000  2182.000000   

       AF4 theta std  AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  \
count    2400.000000  2400.000000    2400.000000  2400.000000   2400.000000   
mean        1.425781     4.058594       1.125000     2.998047      1.815430   
std         0.843262     2.634766       0.511719     1.356445      0.516602   
min         0.138916     0.574707       0.079468     0.762207      0.473145   
25%         0.841797     2.423828       0.768921     2.163086      1.428711   
50%         1.233398     3.263672       1.068359     2.727539      1.777344   
75%         1.806885     4.824219       1.433838     3.441895      2.154297   
max         6.777344    29.484375       3.589844    15.960938      4.140625   

        AF4 beta m  
count  2400.000000  
mean      3.119141  
std       0.609375  
min       1.575195  
25%       2.718262  
50%       3.137695  
75%       3.488281  
max       7.386719  

[8 rows x 113 columns]

In [26]:
def make_data(x, y, window_size):
    x_list=[]
    y_list=[]
    
    for i in range(len(x)-window_size):
        x_list.append(x[i:i+window_size])
        y_list.append(y[i+window_size])

    return np.array(x_list), np.array(y_list)

In [27]:
X = df_train.iloc[:, 1:]
Y  = df_train.iloc[:, 0]

print(X.shape, Y.shape)

(2400, 112) (2400,)


In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)
x_scaled = pd.DataFrame(x_scaled, columns=X.columns)
x_scaled

C:\Users\yhg31\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1544: RuntimeWarning: overflow encountered in multiply
  sqr = np.multiply(arr, arr, out=arr)


AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0          0.247314     0.399170       0.473145    -0.358887      -0.620117   
1         -0.219482    -0.340576       1.063477    -0.089905       0.178955   
2         -0.219482    -0.340576      -0.746094    -0.050079       0.156982   
3         -0.219482     0.029449      -0.293213    -0.097473      -0.407715   
4         -0.452881    -0.340576      -0.250488    -0.283203       0.066650   
...             ...          ...            ...          ...            ...   
2395       0.947266     0.399170       0.959961     1.239258       1.621094   
2396       0.714355     0.399170       0.499756     1.176758      -0.778809   
2397       0.714355     0.399170       0.888184     1.563477       0.251709   
2398       0.247314     0.029449       1.226562     1.279297      -0.366943   
2399       0.013901     0.029449       2.521484     0.091919      -0.435303   

      AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  F7 delta m  ...  \
0       -0.550293      0.433350    1.200195      0.464600   -0.292725  ...   
1        0.280273     -1.248047    0.978027     -0.450195   -0.292725  ...   
2       -0.324463     -1.123047    1.341797     -0.450195   -0.292725  ...   
3       -0.417969     -0.810547    0.586914     -1.365234   -0.292725  ...   
4       -0.908691     -1.095703    0.802246     -1.365234   -0.292725  ...   
...           ...           ...         ...           ...         ...  ...   
2395     0.301025     -0.306885    0.546387      1.378906    1.137695  ...   
2396     0.114197     -0.467041    1.179688      1.378906    1.137695  ...   
2397    -0.896973     -0.541016    0.532715      1.378906    1.137695  ...   
2398    -0.778809      0.491943   -1.589844      0.464600    1.137695  ...   
2399    -0.785156      0.135742   -2.001953      0.464600   -0.292725  ...   

      F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0       -0.841309  -0.030518      -1.378906    -1.405273      -0.800781   
1       -0.639160  -0.318115      -1.258789    -1.265625      -0.742188   
2       -0.338135  -0.142212      -1.078125    -1.171875      -0.017303   
3       -0.801270  -0.630371      -1.138672    -1.171875      -0.242065   
4       -0.928711  -0.522461      -1.438477    -1.452148       0.439941   
...           ...        ...            ...          ...            ...   
2395    -0.642090  -0.019165       0.482910    -0.050049      -0.123840   
2396    -1.543945  -0.394043       0.363037    -0.050049      -0.429688   
2397    -1.185547   0.170288       0.302979    -0.143433       0.079956   
2398    -0.440186  -0.547852       0.122620    -0.423828      -0.415771   
2399    -0.262939  -0.831543      -0.057587    -0.517090       0.610352   

      AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0       -0.716309       0.482910    -0.662598      1.166016    1.256836  
1       -0.625488      -0.028549    -0.622559      0.451416    1.835938  
2       -0.536621       0.769043    -0.929199     -0.693359    1.218750  
3       -0.234619       0.288086    -0.653809     -0.262939    0.634766  
4       -0.253906      -0.691895     0.374512     -0.653809    0.933105  
...           ...            ...          ...           ...         ...  
2395    -0.939941      -0.108704    -0.420654     -0.211792    0.416992  
2396    -0.801758       0.706055    -0.017258      0.905273    0.567383  
2397    -0.445312       1.704102    -0.064758      0.455322    1.663086  
2398    -0.529785       1.353516    -0.522949      0.462891    1.176758  
2399    -0.202637       0.187134    -0.466797      0.058441    0.904297  

[2400 rows x 112 columns]

In [29]:
train, test = make_data(x_scaled, Y, 10)
print(train.shape, test.shape)

(2390, 10, 112) (2390,)


In [30]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test  = train_test_split(train, test, test_size=0.3, random_state=256)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

x_train shape: (1673, 10, 112)
x_test shape: (717, 10, 112)
y_train shape: (1673,)
y_test shape: (717,)


In [31]:
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import LSTM

model = Sequential()
model.add(LSTM(512, input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Dense(4))
model.add(Dense(1, activation='relu'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=["accuracy"])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 512)               1280000   
                                                                 
 dense_2 (Dense)             (None, 4)                 2052      
                                                                 
 dense_3 (Dense)             (None, 1)                 5         
                                                                 
Total params: 1,282,057
Trainable params: 1,282,057
Non-trainable params: 0
_________________________________________________________________


In [32]:
early_stop = EarlyStopping(monitor='accuracy', patience=1, verbose=1)

model.fit(x_train, y_train, epochs=100,
          batch_size=32, verbose=1, callbacks=[early_stop])

Epoch 1/100
53/53 [==============================] - 16s 256ms/step - loss: 0.5975 - accuracy: 0.4543
Epoch 2/100
53/53 [==============================] - 12s 229ms/step - loss: 0.2442 - accuracy: 0.5499
Epoch 3/100
53/53 [==============================] - 16s 298ms/step - loss: 0.1112 - accuracy: 0.6198
Epoch 4/100
53/53 [==============================] - 10s 183ms/step - loss: 0.0575 - accuracy: 0.6533
Epoch 5/100
53/53 [==============================] - 11s 205ms/step - loss: 0.0567 - accuracy: 0.6533
Epoch 00005: early stopping


In [33]:
print("정확도 : %.2f"%(model.evaluate(x_test, y_test, batch_size=32)[1]))

23/23 [==============================] - 2s 51ms/step - loss: 0.0528 - accuracy: 0.6290
정확도 : 0.63


In [34]:
lstm_train_pred = model.predict(x_train).astype(int)
lstm_test_pred = model.predict(x_test).astype(int)

In [35]:
from sklearn.metrics import confusion_matrix
print("LSTM train\n", confusion_matrix(y_train, lstm_train_pred))
print()
print("LSTM test\n", confusion_matrix(y_test, lstm_test_pred))

LSTM train
 [[571   1   0]
 [155 395   0]
 [  1 341 209]]

LSTM test
 [[227   1   0]
 [ 66 174   0]
 [  2 183  64]]


In [36]:
df_test

AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0      3568.155763  2062.071329       1.202268     2.825348       1.343916   
1      3568.611785  2062.158824       0.807665     2.149917       0.737218   
2      3570.473597  2065.758881       1.277113     1.959388       0.718773   
3      3571.612568  2065.197847       0.751001     2.374316       0.388452   
4      3573.342020  2066.813741       1.373842     2.725404       1.016329   
..             ...          ...            ...          ...            ...   
475    3580.266554  2069.890414       1.812120     3.738168       0.735718   
476    3578.462843  2067.762354       1.310612     3.891495       0.845336   
477    3573.877913  2066.994343       0.839764     2.361970       0.922445   
478    3573.129417  2066.445913       1.027406     1.907314       1.373185   
479    3571.731099  2065.153131       0.638391     1.474105       0.713962   

     AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std   F7 delta m  ...  \
0       2.178237      2.359916    4.759368   3572.377430  2065.918528  ...   
1       1.718518      2.961613    4.855673   3574.563695  2066.940235  ...   
2       1.859648      3.557830    3.717402   3575.825018  2067.265706  ...   
3       2.258995      3.700512    3.848984   3577.477852  2066.973515  ...   
4       2.049024      2.529920    4.259767   3576.460200  2066.810671  ...   
..           ...           ...         ...           ...          ...  ...   
475     1.392555      2.964396    3.266624   3577.411198  2068.449777  ...   
476     1.155628      3.246059    3.623907   3577.819349  2068.166233  ...   
477     1.985119      2.941112    3.922317   3575.503029  2067.662293  ...   
478     2.144514      2.512345    4.528844   3574.479851  2066.324512  ...   
479     2.440439      2.081859    4.509923   3573.760981  2066.682373  ...   

     F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0       3.617901   7.416028    3562.066662  2064.686984       0.585269   
1       3.872993   7.974403    3567.086712  2071.634092       1.182088   
2       3.916257   9.038238    3575.568359  2085.892540       1.496764   
3       3.502339   9.010397    3593.995966  2087.384297       0.846248   
4       4.993057   6.320207    3604.352331  2088.075184       1.098990   
..           ...        ...            ...          ...            ...   
475     8.191488  20.017172    3571.441903  2096.272871       1.123283   
476     8.056348  12.008732    3552.249977  2066.165745       1.424949   
477     4.897901   6.931552    3543.990021  2051.712944       0.643122   
478     3.993686  11.547497    3546.960508  2058.890133       1.027444   
479     4.049831  10.418515    3554.581159  2069.492496       1.659622   

     AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0       3.732275       0.961298     1.804823      1.180621    3.035217  
1       3.727645       0.395608     2.453909      1.638011    2.757553  
2       5.057133       0.353375     1.349076      1.219331    3.144259  
3       2.405110       0.571349     2.102375      1.128318    2.972746  
4       2.513709       1.311223     2.184654      1.106621    2.675349  
..           ...            ...          ...           ...         ...  
475     9.462601       1.459096     4.458798      1.189135    2.969003  
476     6.501832       0.950610     3.865724      1.313427    2.771271  
477     3.098788       0.925306     2.033190      1.025014    1.923022  
478     4.748822       1.343093     2.397960      0.879429    2.082569  
479     3.239592       0.476347     2.501917      0.966506    2.060108  

[480 rows x 112 columns]

In [37]:
test_scaled = scaler.fit_transform(df_test)
test_scaled = pd.DataFrame(test_scaled, columns=df_test.columns)
test_scaled

AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0        -0.618695    -0.899286       0.319077     0.381127       0.808497   
1        -0.533770    -0.872693      -0.533407    -0.571600      -0.593886   
2        -0.187046     0.221490       0.480769    -0.840350      -0.636522   
3         0.025064     0.050972      -0.655821    -0.255075      -1.400059   
4         0.347139     0.542099       0.689738     0.240151       0.051279   
..             ...          ...            ...          ...            ...   
475       1.636692     1.477207       1.636575     1.668701      -0.597354   
476       1.300788     0.830416       0.553138     1.884977      -0.343971   
477       0.446938     0.596990      -0.464060    -0.272490      -0.165732   
478       0.307546     0.430303      -0.058689    -0.913803       0.876153   
479       0.047138     0.037381      -0.899100    -1.524864      -0.647643   

     AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  F7 delta m  ...  \
0      -0.308420     -0.936348    1.463292     -1.113892   -0.273681  ...   
1      -0.977931      0.272943    1.663616      0.141245    0.854254  ...   
2      -0.772396      1.471219   -0.704095      0.865372    1.213565  ...   
3      -0.190809      1.757981   -0.430393      1.814266    0.890994  ...   
4      -0.496599     -0.594673    0.424075      1.230031    0.711219  ...   
..           ...           ...         ...           ...         ...  ...   
475    -1.452645      0.278536   -1.641757      1.776000    2.520746  ...   
476    -1.797692      0.844623   -0.898574      2.010320    2.207721  ...   
477    -0.589667      0.231741   -0.277851      0.680518    1.651386  ...   
478    -0.357533     -0.629995    0.983780      0.093110    0.174514  ...   
479     0.073436     -1.495185    0.944423     -0.319594    0.569582  ...   

     F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0      -1.797823  -0.572155      -0.227858    -0.451938      -0.996129   
1      -1.546866  -0.396020      -0.048027    -0.102882      -0.272021   
2      -1.504304  -0.060441       0.255808     0.613529       0.109767   
3      -1.911511  -0.069223       0.915932     0.688482      -0.679489   
4      -0.444961  -0.917824       1.286923     0.723195      -0.372842   
..           ...        ...            ...          ...            ...   
475     2.701616   3.402785       0.107988     1.135086      -0.343369   
476     2.568667   0.876580      -0.579516    -0.377638       0.022636   
477    -0.538575  -0.724980      -0.875409    -1.103815      -0.925937   
478    -1.428130   0.731087      -0.768998    -0.743199      -0.459648   
479    -1.372895   0.374958      -0.496007    -0.210486       0.307360   

     AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0      -0.038789      -0.181918    -0.785951     -0.624985    0.917368  
1      -0.040930      -1.392168    -0.243739      0.947445    0.279909  
2       0.574143      -1.482521    -1.166658     -0.491907    1.167705  
3      -0.652787      -1.016183    -0.537392     -0.804792    0.773948  
4      -0.602545       0.566720    -0.468660     -0.879384    0.091186  
..           ...            ...          ...           ...         ...  
475     2.612286       0.883083     1.431038     -0.595714    0.765355  
476     1.242518      -0.204783     0.935616     -0.168420    0.311403  
477    -0.331864      -0.258920    -0.595186     -1.159937   -1.635999  
478     0.431506       0.634904    -0.290476     -1.660431   -1.269713  
479    -0.266723      -1.219433    -0.203636     -1.361075   -1.321279  

[480 rows x 112 columns]

In [42]:
test_scaled.iloc[1]

AF3 delta std   -0.533770
AF3 delta m     -0.872693
AF3 theta std   -0.533407
AF3 theta m     -0.571600
AF3 alpha std   -0.593886
                   ...   
AF4 theta m     -0.040930
AF4 alpha std   -1.392168
AF4 alpha m     -0.243739
AF4 beta std     0.947445
AF4 beta m       0.279909
Name: 1, Length: 112, dtype: float64

In [59]:
x_list=[]
for i in range(len(test_scaled)):
    x_list.append(test_scaled.iloc[i])
np.array(x_list).shape

(480, 112)

In [72]:
a=np.array(x_list)

In [70]:
x_test.shape

(717, 10, 112)

In [74]:
b=a.reshape(a.shape[0], 1, a.shape[1])

In [75]:
model.predict(x_test)

InvalidArgumentError:    Trying to access element 5 in a list with 1 elements.
	 [[node while/TensorArrayV2Read/TensorListGetItem
 (defined at C:\Users\yhg31\Anaconda3\lib\site-packages\keras\backend.py:4638)
]]
	 [[sequential_1/lstm_1/PartitionedCall]] [Op:__inference_predict_function_12968]

Errors may have originated from an input operation.
Input Source operations connected to node while/TensorArrayV2Read/TensorListGetItem:
In[0] while/TensorArrayV2Read/TensorListGetItem/TensorArrayUnstack/TensorListFromTensor:	
In[1] while/Placeholder (defined at C:\Users\yhg31\Anaconda3\lib\site-packages\keras\backend.py:4654)	
In[2] while/TensorArrayV2Read/TensorListGetItem/element_shape:

Operation defined at: (most recent call last)
>>>   File "C:\Users\yhg31\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
>>>     return _run_code(code, main_globals, None,
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\runpy.py", line 87, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
>>>     app.start()
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
>>>     self.io_loop.start()
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\asyncio\base_events.py", line 596, in run_forever
>>>     self._run_once()
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\asyncio\base_events.py", line 1890, in _run_once
>>>     handle._run()
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\asyncio\events.py", line 80, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
>>>     await self.process_one()
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
>>>     await dispatch(*args)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
>>>     await result
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
>>>     reply_content = await reply_content
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
>>>     result = self._run_cell(
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
>>>     return runner(coro)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
>>>     coro.send(None)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
>>>     if (await self.run_code(code, result,  async_=asy)):
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "C:\Users\yhg31\AppData\Local\Temp/ipykernel_2908/1035736403.py", line 1, in <module>
>>>     model.predict(b)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1789, in predict
>>>     tmp_batch_outputs = self.predict_function(iterator)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1621, in predict_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1611, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1604, in run_step
>>>     outputs = model.predict_step(data)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1572, in predict_step
>>>     return self(x, training=False)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 373, in call
>>>     return super(Sequential, self).call(inputs, training=training, mask=mask)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 679, in __call__
>>>     return super(RNN, self).__call__(inputs, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\layers\recurrent_v2.py", line 1254, in call
>>>     runtime) = lstm_with_backend_selection(**normal_lstm_kwargs)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\layers\recurrent_v2.py", line 1649, in lstm_with_backend_selection
>>>     last_output, outputs, new_h, new_c, runtime = defun_standard_lstm(**params)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\layers\recurrent_v2.py", line 1380, in standard_lstm
>>>     last_output, outputs, new_states = backend.rnn(
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\backend.py", line 4654, in rnn
>>>     final_outputs = tf.compat.v1.while_loop(
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\backend.py", line 4638, in _step
>>>     current_input = tuple(ta.read(time) for ta in input_ta)
>>> 
>>>   File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\backend.py", line 4638, in <genexpr>
>>>     current_input = tuple(ta.read(time) for ta in input_ta)
>>> 

Function call stack:
predict_function -> predict_function -> predict_function -> while_body_12594


In [67]:
test_scaled["pred"]=model.predict(a, verbose=0).astype(int)

ValueError: in user code:

    File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\training.py", line 1572, in predict_step
        return self(x, training=False)
    File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\yhg31\Anaconda3\lib\site-packages\keras\engine\input_spec.py", line 263, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_1" is incompatible with the layer: expected shape=(None, 10, 112), found shape=(32, 112, 1)
