## 데이터불러오기

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import mglearn
from matplotlib import font_manager, rc 

font_name=font_manager.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name() 
rc('font', family=font_name) 

In [63]:
df_train = pd.read_csv("C:/users/yhg31/OneDrive/바탕 화면/데이터파일/2021 학술제 데이터/Subject_A.csv")
df_test = pd.read_csv("C:/users/yhg31/OneDrive/바탕 화면/데이터파일/2021 학술제 데이터/Subject_A_testset.csv")

In [64]:
df_train

Class  AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  \
0         1    3569.164550  2063.892754       1.673726     4.444736   
1         1    3568.423670  2063.099248       1.897790     3.728823   
2         1    3568.157929  2062.445859       2.798014     2.574504   
3         1    3567.710021  2062.112673       2.181775     3.610507   
4         1    3565.546124  2063.128867       1.685161     3.384311   
...     ...            ...          ...            ...          ...   
2395      0    3571.642516  2064.414370       0.959251     2.001895   
2396      0    3572.463073  2064.782561       1.589903     2.412798   
2397      0    3571.770270  2064.389711       1.363372     2.840273   
2398      0    3572.332371  2064.237499       1.079402     2.543801   
2399      0    3572.140034  2064.621301       1.125863     2.328660   

      AF3 alpha std  AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  ...  \
0          0.526209     3.002088      1.425022    3.302739   3563.803888  ...   
1          1.304186     1.854353      1.366575    2.546458   3563.560922  ...   
2          1.120537     1.958819      0.982433    2.258622   3563.279981  ...   
3          0.629608     2.155876      0.856275    2.233711   3562.787801  ...   
4          0.677526     1.795798      0.927924    1.909810   3562.655091  ...   
...             ...          ...           ...         ...           ...  ...   
2395       0.794949     2.503957      1.777619    3.245232   3565.162841  ...   
2396       1.956666     2.350485      1.899846    3.153188   3566.251245  ...   
2397       1.546912     2.833793      1.551021    3.198389   3565.629788  ...   
2398       1.079158     2.917060      1.395746    2.917950   3568.379225  ...   
2399       1.283261     2.514298      1.585738    2.953094   3569.206088  ...   

      F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0       45.468326  72.508750    3701.186330  2182.676835      18.192418   
1       36.551948  66.931186    3725.210509  2180.197439       8.820788   
2       40.754308  66.816547    3724.417296  2176.823208      18.159202   
3       38.074628  63.915386    3725.822160  2177.089059      19.737616   
4       35.357384  64.534645    3723.053978  2167.798335       8.429414   
...           ...        ...            ...          ...            ...   
2395    16.914809  30.201028    3614.839719  2110.869674       7.312555   
2396    13.853342  32.914379    3606.052428  2112.294283      10.713851   
2397    15.143285  33.005223    3588.471770  2100.143895       7.489726   
2398    19.656139  30.727312    3570.759838  2088.584374       0.850258   
2399    22.049781  29.933376    3568.675839  2077.927067      11.172103   

      AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0       41.349662      16.004756    42.046467     46.280843   73.565719  
1       38.012788      19.601233    29.431054     38.559351   67.470041  
2       23.612639      14.378291    19.555084     43.210004   67.781924  
3       29.484396      15.793034    25.713513     39.250246   65.031031  
4       26.374975      14.920736    35.675266     33.901687   66.956313  
...           ...            ...          ...           ...         ...  
2395    18.678410       5.641518    17.222921     20.102750   36.967644  
2396    19.046504       9.355400    21.024817     16.494236   39.812220  
2397    20.585322       6.243404    12.443829     17.851648   40.493349  
2398    21.274596       1.610592     9.749205     23.206343   37.054532  
2399    16.071248       2.266540     6.716508     26.142699   36.638771  

[2400 rows x 113 columns]

In [65]:
df_train["Class"].value_counts()

1    800
2    800
0    800
Name: Class, dtype: int64

In [66]:
col_list=df_train.columns[1:]
col_list1=[]
for i in range(len(col_list)):
    col_list1.append(col_list[i].split(" ")[0])
col_list1
set(col_list1)

{'AF3',
 'AF4',
 'F3',
 'F4',
 'F7',
 'F8',
 'FC5',
 'FC6',
 'O1',
 'O2',
 'P7',
 'P8',
 'T7',
 'T8'}

In [67]:
X = df_train.iloc[:, 1:]
Y  = df_train.iloc[:, 0]

print(X.shape, Y.shape)

(2400, 112) (2400,)


In [68]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)
x_scaled = pd.DataFrame(x_scaled, columns=X.columns)
x_scaled

AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0         -1.499118    -0.789168       1.224465     1.895557      -0.973259   
1         -1.818133    -1.276286       1.666847     1.192033       0.797563   
2         -1.932558    -1.677389       3.444212     0.057690       0.379544   
3         -2.125423    -1.881926       2.227536     1.075765      -0.737902   
4         -3.057174    -1.258104       1.247041     0.853483      -0.628831   
...             ...          ...            ...          ...            ...   
2395      -0.432132    -0.468958      -0.186164    -0.505009      -0.361556   
2396      -0.078809    -0.242932       1.058967    -0.101218       2.282727   
2397      -0.377123    -0.484095       0.611716     0.318859       1.350053   
2398      -0.135088    -0.577535       0.051056     0.027518       0.285357   
2399      -0.217906    -0.341927       0.142787    -0.183899       0.749933   

      AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  F7 delta m  ...  \
0        0.868059     -1.376686   -0.016417     -1.564626   -1.001355  ...   
1       -0.579887     -1.476070   -1.916174     -1.691314   -1.229006  ...   
2       -0.448097     -2.129270   -2.639210     -1.837802   -1.588372  ...   
3       -0.199495     -2.343789   -2.701785     -2.094434   -1.779283  ...   
4       -0.653758     -2.221958   -3.515417     -2.163631   -1.929864  ...   
...           ...           ...         ...           ...         ...  ...   
2395     0.239633     -0.777127   -0.160873     -0.856042   -0.005657  ...   
2396     0.046017     -0.569291   -0.392085     -0.288527    0.215724  ...   
2397     0.655743     -1.162436   -0.278541     -0.612567    0.613837  ...   
2398     0.760790     -1.426468   -0.982996      0.821043    1.031549  ...   
2399     0.252678     -1.103403   -0.894715      1.252185    1.094728  ...   

      F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0        0.908551   2.876797       2.164788     2.094941       1.952868   
1        0.300351   2.453551       2.715398     2.025381       0.297166   
2        0.587001   2.444852       2.697219     1.930718       1.947000   
3        0.404216   2.224701       2.729417     1.938176       2.225861   
4        0.218868   2.271693       2.665973     1.677525       0.228021   
...           ...        ...            ...          ...            ...   
2395    -1.039127  -0.333668       0.185809     0.080397       0.030703   
2396    -1.247955  -0.127769      -0.015587     0.120364       0.631616   
2397    -1.159966  -0.120875      -0.418518    -0.220514       0.062005   
2398    -0.852137  -0.293732      -0.824458    -0.544816      -1.111002   
2399    -0.688863  -0.353978      -0.872222    -0.843805       0.712577   

      AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0        1.549775       1.380371     1.786836      0.500526    2.294283  
1        1.327468       1.986692     0.777194      0.022345    1.866175  
2        0.368108       1.106170    -0.013203      0.310354    1.888079  
3        0.759293       1.344678     0.479671      0.065132    1.694879  
4        0.552139       1.197619     1.276934     -0.266097    1.830095  
...           ...            ...          ...           ...         ...  
2395     0.039382      -0.366739    -0.199852     -1.120646   -0.276054  
2396     0.063905       0.259374     0.104423     -1.344116   -0.076275  
2397     0.166424      -0.265269    -0.582334     -1.260053   -0.028438  
2398     0.212344      -1.046303    -0.797991     -0.928444   -0.269952  
2399    -0.134311      -0.935718    -1.040705     -0.746600   -0.299151  

[2400 rows x 112 columns]

In [69]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test  = train_test_split(x_scaled, Y, test_size=0.3)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

x_train shape: (1680, 112)
x_test shape: (720, 112)
y_train shape: (1680,)
y_test shape: (720,)


In [70]:
from sklearn import svm
from sklearn.svm import SVC

svm = SVC()
svm.fit(x_train, y_train)
svm_train_pred = svm.predict(x_train)
svm_test_pred = svm.predict(x_test)

In [71]:
from sklearn.metrics import accuracy_score
print("D SVM train 정확도 : {0:.3f}".format(accuracy_score(y_train, svm_train_pred)))
print("D SVM test  정확도 : {0:.3f}".format(accuracy_score(y_test, svm_test_pred)))

D SVM train 정확도 : 0.878
D SVM test  정확도 : 0.779


In [72]:
from sklearn.metrics import confusion_matrix

print("D SVM train\n", confusion_matrix(y_train, svm_train_pred))
print()
print("D SVM test\n", confusion_matrix(y_test, svm_test_pred))

D SVM train
 [[477  32  38]
 [ 23 487  52]
 [ 15  45 511]]

D SVM test
 [[198  23  32]
 [ 26 184  28]
 [ 19  31 179]]


## 결과

In [57]:
df_test

AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0      3571.535373  2064.554658       0.740541     2.028495       0.516038   
1      3572.563121  2064.936623       1.252056     2.671930       0.713256   
2      3572.002430  2064.884660       1.483551     2.939971       1.197219   
3      3573.198214  2066.619156       1.133447     2.493483       0.926613   
4      3573.420505  2067.453610       0.548622     2.020028       1.095781   
..             ...          ...            ...          ...            ...   
475    3575.239263  2066.001941       1.111209     2.206317       0.755309   
476    3574.291900  2065.586533       1.077451     2.380530       0.882770   
477    3573.760441  2065.700834       1.263640     1.811400       0.955061   
478    3573.819187  2065.533541       1.231882     2.418790       0.805263   
479    3572.508451  2064.688696       0.797631     1.672506       0.504782   

     AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std   F7 delta m  ...  \
0       2.562503      1.930213    3.548060   3568.156164  2062.272409  ...   
1       2.477751      2.145124    3.536442   3567.931011  2062.274465  ...   
2       2.115965      2.069630    3.563456   3569.161555  2062.128718  ...   
3       1.428645      2.151292    3.397032   3568.189587  2062.209375  ...   
4       1.949250      2.218233    3.774695   3567.799999  2062.622113  ...   
..           ...           ...         ...           ...          ...  ...   
475     2.013057      2.577420    2.971357   3567.106366  2061.071453  ...   
476     2.428217      2.443231    2.887739   3567.627116  2061.177491  ...   
477     2.736016      1.989101    3.513045   3567.348680  2061.332290  ...   
478     1.906373      1.957098    3.552182   3567.623035  2061.527424  ...   
479     2.106582      1.541455    3.386817   3568.709432  2062.654961  ...   

     F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0      18.610010  27.349428    3605.267105  2116.414352       7.644688   
1      19.685056  23.626936    3607.365725  2116.803333       6.957563   
2      18.348831  22.438952    3599.316535  2111.558040       5.898518   
3      22.084355  21.164543    3577.810698  2088.851046       2.966512   
4      18.674359  24.972346    3569.417860  2088.697431       2.868074   
..           ...        ...            ...          ...            ...   
475    26.682191  15.344038    3635.974638  2116.876895       2.659176   
476    23.707442  20.677507    3637.258586  2119.313040       3.168938   
477    19.463613  24.310611    3637.802369  2111.941345       5.543585   
478    23.330077  21.052541    3643.108491  2109.973041       4.365375   
479    19.920188  24.062701    3639.234613  2108.094267       3.985185   

     AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0      11.829167       9.457810    15.320481     22.296964   33.798225  
1      10.016906       3.394768    15.609742     24.321803   29.447163  
2       9.342672       3.219781    12.449042     22.927517   27.970611  
3       7.163787       4.124709    11.736024     27.681783   24.967905  
4       7.895042       6.958782    10.421209     23.141260   28.930632  
..           ...            ...          ...           ...         ...  
475     7.500028       0.686533     6.079028     33.682826   17.940695  
476     6.936489       2.683895     7.707409     29.387881   26.040398  
477    10.715309       3.701737     7.050900     24.552078   28.660792  
478    13.210038       5.136452     6.511386     28.678200   24.448077  
479    12.556798       3.171835     5.782741     23.236406   29.227730  

[480 rows x 112 columns]

In [58]:
test_scaled = scaler.fit_transform(df_test)
test_scaled = pd.DataFrame(test_scaled, columns=df_test.columns)
test_scaled

AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0        -1.250055    -0.711448      -0.502687    -0.434973      -1.004151   
1        -0.470199    -0.272949       0.670057     0.658145      -0.525541   
2        -0.895651    -0.332603       1.200804     1.113513       0.648944   
3         0.011711     1.658617       0.398123     0.354984      -0.007765   
4         0.180385     2.616579      -0.942699    -0.449358       0.402775   
..             ...          ...            ...          ...            ...   
475       1.560461     0.950048       0.347139    -0.132877      -0.423487   
476       0.841601     0.473155       0.269743     0.163090      -0.114163   
477       0.438329     0.604374       0.696615    -0.803793       0.061274   
478       0.482906     0.412319       0.623805     0.228090      -0.302257   
479      -0.511682    -0.557571      -0.371797    -1.039757      -1.031469   

     AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  F7 delta m  ...  \
0       0.411779     -0.522456    0.601450      0.528198    0.637999  ...   
1       0.281992     -0.057362    0.570614      0.348876    0.640401  ...   
2      -0.272035     -0.220740    0.642314      1.328936    0.470136  ...   
3      -1.324576     -0.044015    0.200588      0.554817    0.564361  ...   
4      -0.527337      0.100853    1.202989      0.244532    1.046530  ...   
..           ...           ...         ...           ...         ...  ...   
475    -0.429626      0.878178   -0.929244     -0.307907   -0.764984  ...   
476     0.206138      0.587776   -1.151185      0.106841   -0.641108  ...   
477     0.677491     -0.395015    0.508513     -0.114918   -0.460268  ...   
478    -0.592998     -0.464275    0.612390      0.103591   -0.232309  ...   
479    -0.286404     -1.363774    0.173475      0.968845    1.084904  ...   

     F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0      -1.027607   0.289275      -0.200317     0.650067       1.114133   
1      -0.790974  -0.211313      -0.135929     0.667644       0.877202   
2      -1.085096  -0.371070      -0.382888     0.430631       0.512028   
3      -0.262854  -0.542448      -1.042714    -0.595403      -0.498971   
4      -1.013443  -0.030387      -1.300216    -0.602344      -0.532914   
..           ...        ...            ...          ...            ...   
475     0.749195  -1.325170       0.741828     0.670968      -0.604945   
476     0.094410  -0.607943       0.781221     0.781047      -0.429171   
477    -0.839717  -0.119375       0.797905     0.447951       0.389642   
478     0.011347  -0.557509       0.960703     0.359011      -0.016622   
479    -0.739218  -0.152713       0.841848     0.274118      -0.147718   

     AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0       0.041450       1.505333     0.382620     -1.056810    0.407916  
1      -0.262110      -0.442856     0.424708     -0.681206   -0.071524  
2      -0.375046      -0.499084    -0.035181     -0.939843   -0.234224  
3      -0.740017      -0.208310    -0.138926     -0.057935   -0.565090  
4      -0.617529       0.702340    -0.330235     -0.900194   -0.128440  
..           ...            ...          ...           ...         ...  
475    -0.683695      -1.313072    -0.962031      1.055248   -1.339412  
476    -0.778090      -0.671276    -0.725098      0.258543   -0.446913  
477    -0.145125      -0.344221    -0.820622     -0.638490   -0.158174  
478     0.272751       0.116785    -0.899122      0.126898   -0.622369  
479     0.163331      -0.514490    -1.005142     -0.882545   -0.095703  

[480 rows x 112 columns]

In [59]:
df_test["pred_class"]=svm.predict(test_scaled)

In [60]:
df_test

AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0      3571.535373  2064.554658       0.740541     2.028495       0.516038   
1      3572.563121  2064.936623       1.252056     2.671930       0.713256   
2      3572.002430  2064.884660       1.483551     2.939971       1.197219   
3      3573.198214  2066.619156       1.133447     2.493483       0.926613   
4      3573.420505  2067.453610       0.548622     2.020028       1.095781   
..             ...          ...            ...          ...            ...   
475    3575.239263  2066.001941       1.111209     2.206317       0.755309   
476    3574.291900  2065.586533       1.077451     2.380530       0.882770   
477    3573.760441  2065.700834       1.263640     1.811400       0.955061   
478    3573.819187  2065.533541       1.231882     2.418790       0.805263   
479    3572.508451  2064.688696       0.797631     1.672506       0.504782   

     AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std   F7 delta m  ...  \
0       2.562503      1.930213    3.548060   3568.156164  2062.272409  ...   
1       2.477751      2.145124    3.536442   3567.931011  2062.274465  ...   
2       2.115965      2.069630    3.563456   3569.161555  2062.128718  ...   
3       1.428645      2.151292    3.397032   3568.189587  2062.209375  ...   
4       1.949250      2.218233    3.774695   3567.799999  2062.622113  ...   
..           ...           ...         ...           ...          ...  ...   
475     2.013057      2.577420    2.971357   3567.106366  2061.071453  ...   
476     2.428217      2.443231    2.887739   3567.627116  2061.177491  ...   
477     2.736016      1.989101    3.513045   3567.348680  2061.332290  ...   
478     1.906373      1.957098    3.552182   3567.623035  2061.527424  ...   
479     2.106582      1.541455    3.386817   3568.709432  2062.654961  ...   

     F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  AF4 theta m  \
0    27.349428    3605.267105  2116.414352       7.644688    11.829167   
1    23.626936    3607.365725  2116.803333       6.957563    10.016906   
2    22.438952    3599.316535  2111.558040       5.898518     9.342672   
3    21.164543    3577.810698  2088.851046       2.966512     7.163787   
4    24.972346    3569.417860  2088.697431       2.868074     7.895042   
..         ...            ...          ...            ...          ...   
475  15.344038    3635.974638  2116.876895       2.659176     7.500028   
476  20.677507    3637.258586  2119.313040       3.168938     6.936489   
477  24.310611    3637.802369  2111.941345       5.543585    10.715309   
478  21.052541    3643.108491  2109.973041       4.365375    13.210038   
479  24.062701    3639.234613  2108.094267       3.985185    12.556798   

     AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  pred_class  
0         9.457810    15.320481     22.296964   33.798225           1  
1         3.394768    15.609742     24.321803   29.447163           2  
2         3.219781    12.449042     22.927517   27.970611           2  
3         4.124709    11.736024     27.681783   24.967905           2  
4         6.958782    10.421209     23.141260   28.930632           0  
..             ...          ...           ...         ...         ...  
475       0.686533     6.079028     33.682826   17.940695           0  
476       2.683895     7.707409     29.387881   26.040398           0  
477       3.701737     7.050900     24.552078   28.660792           0  
478       5.136452     6.511386     28.678200   24.448077           2  
479       3.171835     5.782741     23.236406   29.227730           1  

[480 rows x 113 columns]

In [61]:
# SVM으로 예측한 subject
df_test["pred_class"].value_counts()

0    195
1    160
2    125
Name: pred_class, dtype: int64